### ISSUE TITLE
Incorrect stride increments?

### ISSUE THREAD

**Issue by WarrenWeckesser** [seberg/unitdtype#2]
This looks like the strides are reversed:

https://github.com/seberg/unitdtype/blob/e62b02284d929ef9ff17215a31b3e8f0576510a1/unitdtype/src/additional_numeric_casts.c.src#L101-L102

(Likewise further down at line 130.)

**Comment by seberg** [comment]
Ooops, thats what you get for not starting to write tests yet :).  Thanks Warren!  Pushed a fix.

(I should also use a fixed branch name for which NumPy version to use, but not going to do that right now.  Just so that there is a single, clear, branch that should always work.)
